apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-virtual-assistant.fullname" . }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ai-virtual-assistant-tls
  labels:
    {{- include "ai-virtual-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: 8888
      protocol: TCP
      targetPort: oauth-proxy
    - name: proxy-http
      port: 8887
      protocol: TCP
      targetPort: proxy-http
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-virtual-assistant.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
